version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ddspassword14882
      MYSQL_DATABASE: ddstest
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  stack:
    image: dds-server:latest
    ports:
      - "9000:9000"
      - "80:8080"
    environment:
      DDS_TELEGRAM_BOT_APIKEY: 892064233:AAFUMkOMYISsfREKniKQqBEU-KWBpXebPZE
    depends_on:
      - "db"

#  front:
#    image: front:latest
#    restart: always
#    deploy:
#      replicas: 1
#    ports:
#      - "80:8080"

#  back:
#    image: back:latest
#    restart: always
#    deploy:
#      replicas: 1
#    depends_on:
#      - "db"
#    ports:
#      - "80:9000"
#      - "9000:9000"
#    network_mode: host
#    networks:
#      - host
