version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ddspassword14882
      MYSQL_DATABASE: ddstest
#    ports:
#      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  stack:
    image: dds-server:latest
    restart: always
    ports:
      - "80:9000"
    environment:
      - DDS_TELEGRAM_BOT_APIKEY=${TG_KEY}
    depends_on:
      - "db"
